services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    restart: always
    network_mode: "host"
    volumes:
      - configjackett:/config/Jackett
      - torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_OPTS='-FlareSolverrURL="http://flaresolverr:8191"'

volumes:
  configjackett: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/jackett
