services:
  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    restart: always
    network_mode: "host"
    volumes:
      - configradarr:/config
      - torrents:/torrents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configradarr: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/radarr
